config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :draft_posts

  root :to => "posts#index"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates_presence_of :name, :message 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  scope :drafts, where(:published => false)
  scope :published, where(:published => true)
  validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.create(params[:comment])
    redirect_to post
  end
  
end

app/controllers/draft_posts_controller.rb
class DraftPostsController < ApplicationController

  def index
    @posts = Post.drafts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :html, :json

  def index
    @posts = Post.published
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
    @comments = @post.comments.order("created_at")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(params[:post])
    respond_with @post
  end
  
  def edit 
    @post = Post.find(params[:id])
  end
  
  def update 
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    respond_with @post
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/draft_posts_helper.rb
module DraftPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/draft_posts/index.html.erb
<%= link_to "New Post", new_post_path %>

<ul>
  <% @posts.each do |post| %>
    <%= render :partial => 'posts/post', :locals => {:post => post} %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.erb
<% form_for post do |f| -%>

  <% if post.errors.any? %>  
    <div id="errorExplanation">  
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>  
      <ul>  
      <% post.errors.full_messages.each do |msg| %>  
        <li><%= msg %></li>  
      <% end %>  
      </ul>  
    </div>  
  <% end %>

  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>

  <%= f.label :body, "Body" %>
  <%= f.text_area :body %>

  <%= f.submit "Save" %>
<% end -%>

app/views/posts/_post.html.erb
<li>
  <h2><%= link_to post.title, post %></h2>
  <p> <%= link_to "Edit", edit_post_path(post) %></p> 
</li>

app/views/posts/edit.html.erb
<%= render :partial => 'form', :locals => {:post => @post} %>

app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <h2><%= link_to post.title, post %></h2>
      <p> <%= link_to "Edit", edit_post_path(post) %></p> 
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<% form_for @post do |f| -%>

  <% if @post.errors.any? %>  
    <div id="errorExplanation">  
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>  
      <ul>  
      <% @post.errors.full_messages.each do |msg| %>  
        <li><%= msg %></li>  
      <% end %>  
      </ul>  
    </div>  
  <% end %>

  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>

  <%= f.label :body, "Body" %>
  <%= f.text_area :body %>

  <%= f.submit "Save" %>
<% end -%>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>
<p><%= pluralize(@comments.count, 'Comment') %></p>
<% @comments.each do |comment|  %>
  <p><%= comment.message %></p>
  <p><%= comment.name %></p>
<% end %>

<%= form_for :comment, @comment, :url => post_comments_path(@post, @comment) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :message, "Message" %>
  <%= f.text_area :message %>
  <%= f.submit "Add Comment" %>
  
<% end %>